name: CI-CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: cd ./my-library && npm install && npm run build && cd ..
            - uses: KengoTODA/actions-setup-docker-compose@main
              with:
                  version: '1.29.2'
            - name: Docker-Compose Up
              env:
                  PG_DB: ${{ secrets.ENV_PG_DB }}
                  PG_USER: ${{ secrets.ENV_PG_USER }}
                  PG_PASS: ${{ secrets.ENV_PG_PASS }}
                  HOST_NAME: ${{ secrets.ENV_HOST_NAME }}
                  JWT_SECRET: ${{ secrets.ENV_JWT }}
              run: docker-compose up
