name: CI-CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - uses: KengoTODA/actions-setup-docker-compose@main
              with:
                  version: '1.29.2'
            - name: Create Env file
              run: PG_PASS="${{secrets.ENV_PG_PASS}}"  PG_USER="${{secrets.ENV_PG_USER}}" PG_DB="${{secrets.ENV_PG_DB}}" JWT="${{secrets.ENV_JWT}}" HOST_NAME="${{secrets.HOST_NAME}}"
            - name: Docker-Compose Up
              run: docker-compose up
