name: CI-CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - uses: KengoTODA/actions-setup-docker-compose@main
              with:
                  version: '1.29.2'
              env:
                  PG_DB: ${{ secrets.ENV_PG_DB }}
                  PG_USER: ${{ secrets.ENV_PG_USER }}
                  PG_PASS: ${{ secrets.ENV_PG_PASS }}
                  HOST_NAME: ${{ secrets.ENV_HOST_NAME }}
                  JWT_SECRET: ${{ secrets.ENV_JWT }}
            - name: Docker-Compose Up
              run: docker-compose up
